# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake #for auto code refactoring like removing unused imports and variables
        args:
          - --recursive
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --expand-star-imports
          - --exclude
          - __init__.py
          - --remove-duplicate-keys
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort #for sorting the import statements
        name: isort (python)
        args:
          - --force-single-line-imports
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black # for consistent code formatting
        args:
          - "-l 100"
ci:
  autofix_commit_msg: "[pre-commit.ci] Auto-fix from pre-commit"
  autoupdate_commit_msg: "[pre-commit.ci] Auto-update from pre-commit"

#mypy is code linter. used for issues like adding incorrect return types or not mentioning return types
#command: pre-commit run --all-files
