swagger: '2.0'
info:
  title: Cloud Endpoints + Cloud Run
  description: Sample API on Cloud Endpoints with a Cloud Run backend
  version: 1.0.0
host: proxy-s75wuozpva-uc.a.run.app
schemes:
  - https

produces:
  - application/json
x-google-backend:
  address: https://dls-s75wuozpva-uc.a.run.app
  protocol: h2

security:
  - api_key: [ ]
# api_key for public use should be created in project 1 under org1
# api_key for private use should be created in project 2 under org1

paths:
  /v1/healthcheck:
    get:
      summary: Healthcheck
      operationId: id-healthcheck
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      x-google-quota:
        metricCosts:
          "api_requests": 1

securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"


x-google-management:
  metrics:
    - name: api_requests
      valueType: INT64
      metricKind: DELTA
  quota:
      limits:
      - name: limit-on-api-requests
        values:
          STANDARD: 5
        unit: "1/min/{project}"
        metric: api_requests
